language: node_js
node_js:
  - 12.18.3
script:
  - npm install
  - npm run build
  
env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
- sshpass -p "F5f3Y1f7" scp -P 2285 -r ./ test20@test20.f5-cloud.top:/var/www/test20/data/www/test20.f5-cloud.top/
