language: node_js
node_js:
  - 12.18.3
script:
  - npm install
  - npm run build
  
env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
- ls -l
